// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer_gui/proto/web.proto

package server // import "jlambert/lightningCab/customer_server/customer_gui/proto/server"

/*
Web exposes a backend server over gRPC.
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/johanbrandhorst/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{0}
}
func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (dst *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(dst, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

type SaveMessageRespons struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveMessageRespons) Reset()         { *m = SaveMessageRespons{} }
func (m *SaveMessageRespons) String() string { return proto.CompactTextString(m) }
func (*SaveMessageRespons) ProtoMessage()    {}
func (*SaveMessageRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{1}
}
func (m *SaveMessageRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMessageRespons.Unmarshal(m, b)
}
func (m *SaveMessageRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMessageRespons.Marshal(b, m, deterministic)
}
func (dst *SaveMessageRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMessageRespons.Merge(dst, src)
}
func (m *SaveMessageRespons) XXX_Size() int {
	return xxx_messageInfo_SaveMessageRespons.Size(m)
}
func (m *SaveMessageRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMessageRespons.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMessageRespons proto.InternalMessageInfo

func (m *SaveMessageRespons) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *SaveMessageRespons) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type SaveMessageRequest struct {
	ObjectToSave         *DBObject `protobuf:"bytes,1,opt,name=objectToSave" json:"objectToSave,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveMessageRequest) Reset()         { *m = SaveMessageRequest{} }
func (m *SaveMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SaveMessageRequest) ProtoMessage()    {}
func (*SaveMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{2}
}
func (m *SaveMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveMessageRequest.Unmarshal(m, b)
}
func (m *SaveMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveMessageRequest.Marshal(b, m, deterministic)
}
func (dst *SaveMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMessageRequest.Merge(dst, src)
}
func (m *SaveMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SaveMessageRequest.Size(m)
}
func (m *SaveMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMessageRequest proto.InternalMessageInfo

func (m *SaveMessageRequest) GetObjectToSave() *DBObject {
	if m != nil {
		return m.ObjectToSave
	}
	return nil
}

type LoadMessageRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMessageRequest) Reset()         { *m = LoadMessageRequest{} }
func (m *LoadMessageRequest) String() string { return proto.CompactTextString(m) }
func (*LoadMessageRequest) ProtoMessage()    {}
func (*LoadMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{3}
}
func (m *LoadMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMessageRequest.Unmarshal(m, b)
}
func (m *LoadMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMessageRequest.Marshal(b, m, deterministic)
}
func (dst *LoadMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMessageRequest.Merge(dst, src)
}
func (m *LoadMessageRequest) XXX_Size() int {
	return xxx_messageInfo_LoadMessageRequest.Size(m)
}
func (m *LoadMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMessageRequest proto.InternalMessageInfo

func (m *LoadMessageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LoadMessageResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments" json:"comments,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Jsondata             string   `protobuf:"bytes,4,opt,name=jsondata" json:"jsondata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadMessageResponse) Reset()         { *m = LoadMessageResponse{} }
func (m *LoadMessageResponse) String() string { return proto.CompactTextString(m) }
func (*LoadMessageResponse) ProtoMessage()    {}
func (*LoadMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{4}
}
func (m *LoadMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadMessageResponse.Unmarshal(m, b)
}
func (m *LoadMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadMessageResponse.Marshal(b, m, deterministic)
}
func (dst *LoadMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadMessageResponse.Merge(dst, src)
}
func (m *LoadMessageResponse) XXX_Size() int {
	return xxx_messageInfo_LoadMessageResponse.Size(m)
}
func (m *LoadMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadMessageResponse proto.InternalMessageInfo

func (m *LoadMessageResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *LoadMessageResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *LoadMessageResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoadMessageResponse) GetJsondata() string {
	if m != nil {
		return m.Jsondata
	}
	return ""
}

type DBObject struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Jsondata             string   `protobuf:"bytes,4,opt,name=jsondata" json:"jsondata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DBObject) Reset()         { *m = DBObject{} }
func (m *DBObject) String() string { return proto.CompactTextString(m) }
func (*DBObject) ProtoMessage()    {}
func (*DBObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{5}
}
func (m *DBObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DBObject.Unmarshal(m, b)
}
func (m *DBObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DBObject.Marshal(b, m, deterministic)
}
func (dst *DBObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DBObject.Merge(dst, src)
}
func (m *DBObject) XXX_Size() int {
	return xxx_messageInfo_DBObject.Size(m)
}
func (m *DBObject) XXX_DiscardUnknown() {
	xxx_messageInfo_DBObject.DiscardUnknown(m)
}

var xxx_messageInfo_DBObject proto.InternalMessageInfo

func (m *DBObject) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DBObject) GetJsondata() string {
	if m != nil {
		return m.Jsondata
	}
	return ""
}

type ListOfObjects struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Jsondata             string   `protobuf:"bytes,4,opt,name=jsondata" json:"jsondata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfObjects) Reset()         { *m = ListOfObjects{} }
func (m *ListOfObjects) String() string { return proto.CompactTextString(m) }
func (*ListOfObjects) ProtoMessage()    {}
func (*ListOfObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{6}
}
func (m *ListOfObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfObjects.Unmarshal(m, b)
}
func (m *ListOfObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfObjects.Marshal(b, m, deterministic)
}
func (dst *ListOfObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfObjects.Merge(dst, src)
}
func (m *ListOfObjects) XXX_Size() int {
	return xxx_messageInfo_ListOfObjects.Size(m)
}
func (m *ListOfObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfObjects.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfObjects proto.InternalMessageInfo

func (m *ListOfObjects) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListOfObjects) GetJsondata() string {
	if m != nil {
		return m.Jsondata
	}
	return ""
}

type ListOfObjectsRespons struct {
	Acknack              bool        `protobuf:"varint,1,opt,name=acknack" json:"acknack,omitempty"`
	Comments             string      `protobuf:"bytes,2,opt,name=comments" json:"comments,omitempty"`
	ListOfDBObjects      []*DBObject `protobuf:"bytes,3,rep,name=listOfDBObjects" json:"listOfDBObjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListOfObjectsRespons) Reset()         { *m = ListOfObjectsRespons{} }
func (m *ListOfObjectsRespons) String() string { return proto.CompactTextString(m) }
func (*ListOfObjectsRespons) ProtoMessage()    {}
func (*ListOfObjectsRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_web_35dcdbdd71961efc, []int{7}
}
func (m *ListOfObjectsRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfObjectsRespons.Unmarshal(m, b)
}
func (m *ListOfObjectsRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfObjectsRespons.Marshal(b, m, deterministic)
}
func (dst *ListOfObjectsRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfObjectsRespons.Merge(dst, src)
}
func (m *ListOfObjectsRespons) XXX_Size() int {
	return xxx_messageInfo_ListOfObjectsRespons.Size(m)
}
func (m *ListOfObjectsRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfObjectsRespons.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfObjectsRespons proto.InternalMessageInfo

func (m *ListOfObjectsRespons) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *ListOfObjectsRespons) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *ListOfObjectsRespons) GetListOfDBObjects() []*DBObject {
	if m != nil {
		return m.ListOfDBObjects
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "web.EmptyParameter")
	proto.RegisterType((*SaveMessageRespons)(nil), "web.SaveMessageRespons")
	proto.RegisterType((*SaveMessageRequest)(nil), "web.SaveMessageRequest")
	proto.RegisterType((*LoadMessageRequest)(nil), "web.LoadMessageRequest")
	proto.RegisterType((*LoadMessageResponse)(nil), "web.LoadMessageResponse")
	proto.RegisterType((*DBObject)(nil), "web.DBObject")
	proto.RegisterType((*ListOfObjects)(nil), "web.listOfObjects")
	proto.RegisterType((*ListOfObjectsRespons)(nil), "web.listOfObjectsRespons")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CustomerUIMethods service

type CustomerUIMethodsClient interface {
	// Ask taxi for Price
	SaveToDB(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageRespons, error)
	// Accept price from Taxi
	LoadFromDB(ctx context.Context, in *LoadMessageRequest, opts ...grpc.CallOption) (*LoadMessageResponse, error)
	// Halt payment of incoming paymentRequests
	ListAllObjectsInDB(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*ListOfObjectsRespons, error)
}

type customerUIMethodsClient struct {
	cc *grpc.ClientConn
}

func NewCustomerUIMethodsClient(cc *grpc.ClientConn) CustomerUIMethodsClient {
	return &customerUIMethodsClient{cc}
}

func (c *customerUIMethodsClient) SaveToDB(ctx context.Context, in *SaveMessageRequest, opts ...grpc.CallOption) (*SaveMessageRespons, error) {
	out := new(SaveMessageRespons)
	err := grpc.Invoke(ctx, "/web.CustomerUIMethods/SaveToDB", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerUIMethodsClient) LoadFromDB(ctx context.Context, in *LoadMessageRequest, opts ...grpc.CallOption) (*LoadMessageResponse, error) {
	out := new(LoadMessageResponse)
	err := grpc.Invoke(ctx, "/web.CustomerUIMethods/LoadFromDB", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerUIMethodsClient) ListAllObjectsInDB(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*ListOfObjectsRespons, error) {
	out := new(ListOfObjectsRespons)
	err := grpc.Invoke(ctx, "/web.CustomerUIMethods/ListAllObjectsInDB", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CustomerUIMethods service

type CustomerUIMethodsServer interface {
	// Ask taxi for Price
	SaveToDB(context.Context, *SaveMessageRequest) (*SaveMessageRespons, error)
	// Accept price from Taxi
	LoadFromDB(context.Context, *LoadMessageRequest) (*LoadMessageResponse, error)
	// Halt payment of incoming paymentRequests
	ListAllObjectsInDB(context.Context, *EmptyParameter) (*ListOfObjectsRespons, error)
}

func RegisterCustomerUIMethodsServer(s *grpc.Server, srv CustomerUIMethodsServer) {
	s.RegisterService(&_CustomerUIMethods_serviceDesc, srv)
}

func _CustomerUIMethods_SaveToDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerUIMethodsServer).SaveToDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.CustomerUIMethods/SaveToDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerUIMethodsServer).SaveToDB(ctx, req.(*SaveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerUIMethods_LoadFromDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerUIMethodsServer).LoadFromDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.CustomerUIMethods/LoadFromDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerUIMethodsServer).LoadFromDB(ctx, req.(*LoadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerUIMethods_ListAllObjectsInDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerUIMethodsServer).ListAllObjectsInDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.CustomerUIMethods/ListAllObjectsInDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerUIMethodsServer).ListAllObjectsInDB(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerUIMethods_serviceDesc = grpc.ServiceDesc{
	ServiceName: "web.CustomerUIMethods",
	HandlerType: (*CustomerUIMethodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveToDB",
			Handler:    _CustomerUIMethods_SaveToDB_Handler,
		},
		{
			MethodName: "LoadFromDB",
			Handler:    _CustomerUIMethods_LoadFromDB_Handler,
		},
		{
			MethodName: "ListAllObjectsInDB",
			Handler:    _CustomerUIMethods_ListAllObjectsInDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer_gui/proto/web.proto",
}

func init() { proto.RegisterFile("customer_gui/proto/web.proto", fileDescriptor_web_35dcdbdd71961efc) }

var fileDescriptor_web_35dcdbdd71961efc = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x6e, 0x08, 0x82, 0xee, 0x85, 0xc1, 0xf0, 0x90, 0x08, 0x11, 0x87, 0xca, 0x07, 0xb4, 0x53,
	0x23, 0xc6, 0x81, 0x5d, 0xf8, 0x58, 0x57, 0x86, 0x86, 0x36, 0x0d, 0x85, 0x71, 0xe1, 0x82, 0xec,
	0xf4, 0x5d, 0x3e, 0x1a, 0xdb, 0xc5, 0x76, 0x36, 0xf5, 0x8c, 0xf8, 0x9b, 0xfc, 0x10, 0x4e, 0x28,
	0x4e, 0x53, 0xa9, 0x4d, 0x85, 0xc4, 0xb8, 0xf9, 0xcd, 0xf3, 0xa1, 0xc7, 0x79, 0x5e, 0xc3, 0xb3,
	0xa4, 0x32, 0x56, 0x09, 0xd4, 0xdf, 0xd2, 0x2a, 0x8f, 0x66, 0x5a, 0x59, 0x15, 0x5d, 0x23, 0x1f,
	0xba, 0x13, 0xf1, 0xaf, 0x91, 0x87, 0x07, 0x69, 0x6e, 0xb3, 0x8a, 0x0f, 0x13, 0x25, 0xa2, 0x42,
	0x65, 0x4c, 0x72, 0xcd, 0xe4, 0x24, 0x53, 0xda, 0xd8, 0x46, 0xc0, 0xab, 0xcb, 0x85, 0x32, 0x55,
	0xb3, 0x0c, 0x75, 0x61, 0x1a, 0x39, 0xdd, 0x81, 0x07, 0xef, 0xc5, 0xcc, 0xce, 0x3f, 0x31, 0xcd,
	0x04, 0x5a, 0xd4, 0xf4, 0x23, 0x90, 0xcf, 0xec, 0x0a, 0xcf, 0xd0, 0x18, 0x96, 0x62, 0x8c, 0x66,
	0xa6, 0xa4, 0x21, 0x01, 0xdc, 0x65, 0xc9, 0x54, 0xb2, 0x64, 0x1a, 0x78, 0x03, 0x6f, 0xaf, 0x1f,
	0xb7, 0x23, 0x09, 0xa1, 0x9f, 0x28, 0x21, 0x50, 0x5a, 0x13, 0xdc, 0x1a, 0x78, 0x7b, 0x5b, 0xf1,
	0x72, 0xa6, 0x1f, 0xd6, 0xbc, 0xbe, 0x57, 0x68, 0x2c, 0x79, 0x01, 0xf7, 0x15, 0x2f, 0x30, 0xb1,
	0x17, 0xaa, 0x46, 0x9d, 0xe1, 0xbd, 0xfd, 0xed, 0x61, 0x7d, 0xa9, 0xf1, 0xe8, 0xdc, 0x41, 0xf1,
	0x0a, 0x85, 0x3e, 0x07, 0x72, 0xaa, 0xd8, 0x64, 0xcd, 0x68, 0x07, 0xfc, 0x29, 0xce, 0x9d, 0x7e,
	0x2b, 0xae, 0x8f, 0x74, 0x0e, 0xbb, 0x2b, 0x3c, 0x17, 0x1e, 0x6f, 0x96, 0xbe, 0xb5, 0xf7, 0x97,
	0xf6, 0x35, 0xbb, 0x30, 0x4a, 0x4e, 0x98, 0x65, 0xc1, 0xed, 0x86, 0xdd, 0xce, 0xf4, 0x00, 0xfa,
	0x6d, 0xf8, 0x6e, 0xb0, 0xbf, 0x2a, 0x5f, 0xc3, 0x76, 0x99, 0x1b, 0x7b, 0x7e, 0xd9, 0xa8, 0xcd,
	0x3f, 0xca, 0x7f, 0x7a, 0xf0, 0x78, 0x45, 0xff, 0x5f, 0x9d, 0x91, 0x57, 0xf0, 0xb0, 0x71, 0x6b,
	0x6f, 0x63, 0x02, 0x7f, 0xe0, 0x77, 0x0b, 0x5a, 0x67, 0xed, 0xff, 0xf2, 0xe0, 0xd1, 0xd1, 0x62,
	0x55, 0xbf, 0x9c, 0x9c, 0xa1, 0xcd, 0xd4, 0xc4, 0x90, 0x37, 0xd0, 0xaf, 0x1b, 0xbc, 0x50, 0xe3,
	0x11, 0x79, 0xe2, 0x1c, 0xba, 0x1b, 0x11, 0x6e, 0x00, 0xdc, 0x15, 0x68, 0x8f, 0x1c, 0x02, 0xd4,
	0x8d, 0x1e, 0x6b, 0x25, 0x96, 0x0e, 0xdd, 0x55, 0x08, 0x83, 0x2e, 0xd0, 0x74, 0x4f, 0x7b, 0xe4,
	0x18, 0xc8, 0x69, 0x6e, 0xec, 0x61, 0x59, 0x2e, 0xa2, 0x9e, 0xc8, 0xf1, 0x88, 0xec, 0x3a, 0xc5,
	0xea, 0xf2, 0x87, 0x4f, 0xdd, 0xc7, 0x4d, 0x7f, 0x93, 0xf6, 0x46, 0x3f, 0xbc, 0xdf, 0xef, 0xde,
	0x16, 0x25, 0x13, 0x1c, 0xb5, 0x8d, 0xca, 0x3c, 0xcd, 0xac, 0xcc, 0x65, 0x7a, 0xc4, 0x78, 0xb4,
	0x7c, 0xa2, 0x06, 0xf5, 0x15, 0xea, 0x68, 0xc3, 0x93, 0x4d, 0xca, 0x1c, 0xa5, 0xfd, 0x7a, 0x73,
	0x83, 0x06, 0xe1, 0x77, 0xdc, 0xf4, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xeb, 0xb1,
	0x18, 0x17, 0x04, 0x00, 0x00,
}
